---
title: "data process"
author: "Kanyan Chen"
date: "09/18/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidytext)
```

```{r}
# load lyrics data
load('../output/processed_lyrics.RData')
```

```{r}
dt_lyrics = dt_lyrics[dt_lyrics$year>=1970&dt_lyrics$genre!="Not Available",]
```

```{r warning=FALSE}
bing = get_sentiments("bing")
affin = get_sentiments("afinn")
nrc = get_sentiments("nrc")
n = dim(dt_lyrics)[1]

dt_lyrics$affin.mean = rep(0,n)
dt_lyrics$affin.count = rep(0,n)

dt_lyrics$bing.mean = rep(0,n)
dt_lyrics$bing.count = rep(0,n)

dt_lyrics$nrc.count = rep(0,n)

dt_lyrics$lyrics.length = rep(0,n)

for(i in 1:3){
  a = unlist(strsplit(dt_lyrics[i,"stemmedwords"][[1]]," ")[[1]])
  b = unlist(strsplit(dt_lyrics[i,"lyrics"][[1]]," ")[[1]])
  dt_lyrics$lyrics.length[i] = length(b)
  A = data.frame(word=a)
  affin.v = (A%>%inner_join(affin,"word"))$value
  if(length(affin.v)==0){
    dt_lyrics$affin.mean[i] = 0
    dt_lyrics$affin.count[i] = 0
  }
  else{
    dt_lyrics$affin.mean[i] = mean(affin.v)
    dt_lyrics$affin.count[i] = length(affin.v)
  }
  bing.v = (A%>%inner_join(bing,"word"))$sentiment
  if(length(bing.v)==0){
    dt_lyrics$bing.mean[i] = 0.5
    dt_lyrics$bing.count[i] = 0
  }
  else{
    dt_lyrics$bing.mean[i] = mean(bing.v=="positive")
    dt_lyrics$bing.count[i] = length(bing.v)
  }
  nrc.v = (A%>%inner_join(nrc,"word"))$sentiment
  dt_lyrics$nrc.count[i] = length(nrc.v)
}
```

```{r}
dt_lyrics = dt_lyrics[,c("year","genre","affin.mean","affin.count","bing.mean","bing.count","lyrics.length","nrc.count")]
save(dt_lyrics,file="../output/processed1_lyrics.RData")
```
